/* eslint-disable sort-keys-fix/sort-keys-fix */

// Source list must be manually updated with new liquidity sources
// 0x: https://explorer.0xprotocol.org/liquiditySources
// 1inch: https://docs.1inch.io/docs/educational-resources/intermediate/1inch-Liquidity-Sources/
// Accompanying badge icons should be updated at: https://github.com/rainbow-me/assets/tree/master/exchanges

const oneinch = {
  AAVE: 'Aave',
  AAVE_LIQUIDATOR: 'Aave',
  AAVE_V2: 'Aave',
  AAVE_V3: 'Aave',
  AERODROME: 'Aerodrome',
  AERODROME_V3: 'Aerodrome',
  ALIEN_BASE: 'AlienBase',
  APESWAP: 'ApeSwap',
  ARBIDEX: 'Arbidex',
  ARBIDEX_V3: 'Arbidex',
  ARBSWAP: 'ArbSwap',
  ARBSWAP_STABLE: 'ArbSwap',
  AURORASWAP: 'AuroraSwap',
  AXIAL: 'Axial',
  BAGUETTE: 'Baguette',
  BALANCER: 'Balancer',
  BALANCER_V2: 'Balancer',
  BANCOR: 'Bancor',
  BASTION: 'Bastion',
  BAOFINANCE: 'Bao Finance',
  BGD_AAVE_STATIC: 'Bored Ghosts',
  BLACKHOLESWAP: 'BlackHoleSwap',
  BLUEPRINT: 'Blueprint',
  BOBSWAP: 'BobSwap',
  CANARY: 'Canary',
  CAMELOT: 'Camelot',
  CAMELOT_V3: 'Camelot',
  CARBON: 'Carbon',
  CHAI: 'Chai',
  CHRONOS: 'Chronos',
  CHRONOS_V3: 'Chronos',
  CLAIMSWAP: 'Claim Swap',
  CLAYSTACK: 'Claystack',
  CLIPPER: 'Clipper',
  CLIPPER_COVES: 'Clipper Coves',
  COFIX: 'CoFix',
  COMETH: 'Cometh',
  COMPOUND: 'Compound',
  COMPOUND_V3: 'Compound',
  CONVERGENCE_X: 'Convergence X',
  CREAM_LENDING: 'Cream Swap',
  CREAMSWAP: 'Cream Swap',
  CURVE: 'Curve',
  CURVE_LLAMMA: 'Curve',
  CURVE_SGT: 'Curve',
  CURVE_STABLE_NG: 'Curve',
  CURVE_V2: 'Curve',
  CURVE_V2_ETH_CRV: 'Curve',
  CURVE_V2_ETH_CVX: 'Curve',
  CURVE_V2_EURS_2_ASSET: 'Curve',
  CURVE_V2_EURT_2_ASSET: 'Curve',
  CURVE_V2_SPELL_2_ASSET: 'Curve',
  CURVE_V2_THRESHOLDNETWORK_2_ASSET: 'Curve',
  CURVE_V2_TRICRYPTO_NG: 'Curve',
  CURVE_V2_TWO_CRYPTO: 'Curve',
  CURVE_V2_TWOCRYPTO_META: 'Curve',
  CURVE_V2_TWOCRYPTO_NG: 'Curve',
  CURVE_V2_XAUT_2_ASSET: 'Curve',
  CURVE_V2_YFI_2_ASSET: 'Curve',
  DACKIE_SWAP: 'DackieSwap',
  DEFI_PLAZA: 'DefiPlaza',
  DEFISWAP: 'DefiSwap',
  DFX_FINANCE: 'DFX',
  DFX_FINANCE_V3: 'DFX',
  DFYN: 'Dfyn',
  DODO: 'DODO',
  DODO_V2: 'DODO',
  DODO_V3: 'DODO',
  DXSWAP: 'Swapr',
  DYSTOPIA: 'Dystopia',
  ELASTICSWAP: 'ElasticSwap',
  ELK: 'ELK',
  ELKFINANCE: 'ELK',
  EQUALIZER: 'Equalizer',
  FIREBIRD_FINANCE: 'Firebird',
  FIXED_FEE_SWAP: '1inch',
  FIXED_FEE_SWAP_V3: '1inch',
  GEM: 'GemSwap',
  GEISTFINANCE: 'Geistfinance',
  GMX: 'GMX',
  GRAVITY: 'Gravity',
  HAKUSWAP: 'Hakuswap',
  HOLD: 'Holdr',
  HONEYSWAP: 'HoneySwap',
  HORIZON_DEX: 'HorizonDex',
  IEARN: 'Yearn',
  INDEXED_FINANCE: 'Indexed Finance',
  INTEGRAL: 'Integral',
  IRONSWAP: 'IronSwap',
  JETSWAP: 'JetSwap',
  KLAYSWAP: 'KLAYswap',
  KLAP: 'Klap',
  KYBER: 'KyberSwap',
  KYBER_DMM: 'KyberSwap',
  KYBER_DMM_STATIC: 'KyberSwap',
  KYBERSWAP_ELASTIC: 'KyberSwap',
  LEVINSWAP: 'Levinswap',
  LEVEL_FINANCE: 'Level Finance',
  LIGHTER: 'Lighter',
  LIF3: 'Lif3',
  LIF3_SWAP: 'Lif3',
  LIF3_TRADE: 'Lif3',
  LINKSWAP: 'Linkswap',
  LUASWAP: 'LuaSwap',
  LYDIA: 'Lydia',
  MAVERICK: 'Maverick',
  MAVERICK_V1: 'Maverick',
  METAVAULT_TRADE: 'Metavault Trade',
  MINISWAP: 'MiniSwap',
  MOONISWAP: 'Mooniswap',
  MOONISWAP_MIGRATOR: 'Mooniswap',
  MORPHEUSSWAP: 'MorpheusSwap',
  MSTABLE: 'mStable',
  MUMMY_FINANCE: 'Mummy Finance',
  MUMMY_FINANCE_OPERA: 'Mummy Finance',
  MUTE: 'Mute',
  MYCELIUM: 'Mycelium',
  NEARPAD: 'NearPAD',
  NERVE: 'Nerve Finance',
  NOMISWAP_STABLE: 'Nomiswap',
  NOMISWAPEPCS: 'Nomiswap',
  OASIS: 'Oasis',
  OLIVESWAP: 'OliveSwap',
  ONE_INCH_LIMIT_ORDER: '1inch',
  ONE_INCH_LIMIT_ORDER_V2: '1inch',
  ONE_INCH_LIMIT_ORDER_V3: '1inch',
  ONE_INCH_LIMIT_ORDER_V4: '1inch',
  ONE_INCH_LP: '1inch',
  ONE_INCH_LP_1_1: '1inch',
  ONE_INCH_LP_MIGRATOR: '1inch',
  ONE_INCH_LP_MIGRATOR_V1_1: '1inch',
  ONESWAP: 'Firebird',
  ORIGIN: 'Origin',
  ORIGIN_WOETH: 'Origin',
  PAINTSWAP: 'PaintSwap',
  PANCAKE_STABLE: 'PancakeSwap',
  PANCAKE_SWAP: 'PancakeSwap',
  PANCAKE_SWAP_V2: 'PancakeSwap',
  PANCAKE_SWAP_V3: 'PancakeSwap',
  PANCAKESWAP_V2: 'PancakeSwap',
  PANCAKESWAP_V3: 'PancakeSwap',
  PANGEA_SWAP: 'Pangea Swap',
  PEARL: 'Pearl',
  PLATYPUS_FINANCE: 'Platypus',
  PMM1: 'PMM',
  PMM11: 'PMM',
  PMM15: 'PMM',
  PMM2: 'PMM',
  PMM3: 'PMM',
  PMM4: 'PMM',
  PMM5: 'PMM',
  PMM6: 'PMM',
  PMM7: 'PMM',
  PMM8: 'PMM',
  POLYCAT_FINANCE: 'Polycat',
  POLYDEX_FINANCE: 'Polydex',
  POWERINDEX: 'PowerIndex',
  PROTOFI: 'ProtoFi',
  PSM: 'Maker',
  PSM_GUSD: 'Maker',
  QUICKSWAP: 'QuickSwap',
  QUICKSWAP_V3: 'QuickSwap',
  RAFT_PSM: 'Raft',
  RAMSES: 'Ramses Exchange',
  RAMSES_V2: 'Ramses Exchange',
  RADIOSHACK: 'RadioShack',
  RETRO: 'Retro',
  ROCKET_SWAP: 'RocketSwap',
  ROSE: 'Rose',
  SADDLE: 'Saddle',
  SAFE_SWAP: 'SafeSwap',
  SAKESWAP: 'SakeSwap',
  SATIN: 'Satin',
  SATIN_4POOL: 'Satin',
  SCREAM: 'Scream',
  SETH_WRAPPER: 'sETH',
  SFINANCE: 'sFinance',
  SDAI: 'sDAI',
  SHELL: 'Shell',
  SHELL_OCEAN: 'Shell',
  SHIBASWAP: 'Shiba Swap',
  SMARDEX: 'Smardex',
  SMOOTHY_FINANCE: 'Smoothy Finance',
  SOLIDLIZARD: 'SolidLizard',
  SOLIDLY: 'Solidly',
  SOLIDLY_V3: 'Solidly',
  SPACEFI: 'SpaceFi',
  SPIRITSWAP: 'SpiritSwap',
  SPIRITSWAP_V2: 'SpiritSwap',
  SPOOKYSWAP: 'SpookySwap',
  ST_ETH: 'stETH',
  SWAAP: 'Swaap',
  SWAP: 'BaseSwap',
  SWAP_BASED: 'SwapBased',
  SWAPFISH: 'SwapFish',
  SWAPSICLE: 'SwapSicle',
  SWAPR: 'Swapr',
  SYNAPSE: 'Synapse',
  SYNCSWAP: 'SyncSwap',
  SYNTHETIX: 'Synthetix',
  SYNTHETIX_ATOMIC_SIP288: 'Synthetix',
  SYNTHETIX_SUSD: 'Synthetix',
  SYNTHETIX_WRAPPER: 'Synthetix',
  SYNTHSWAP: 'Synthswap',
  TRADERJOE: 'Trader Joe',
  TRADERJOE_V2: 'Trader Joe',
  TRADERJOE_V2_1: 'Trader Joe',
  TRIDENT: 'Trident',
  TRISOLARIS: 'Trisolaris',
  TRISOLARIS_STABLE: 'Trisolaris',
  UNIFI: 'Unifi',
  UNISWAP_V1: 'Uniswap',
  UNISWAP_V2: 'Uniswap',
  UNISWAP_V2_MIGRATOR: 'Uniswap',
  UNISWAP_V3: 'Uniswap',
  USDFI: 'USDFI',
  VALUELIQUID: 'Value Liquid',
  VELOCIMETER_V2: 'Velocimeter',
  VELODROME: 'Velodrome',
  VELODROME_V2: 'Velodrome',
  VELODROME_V3: 'Velodrome',
  VERSE: 'Verse',
  VIRTUSWAP: 'VirtuSwap',
  WAULTSWAP: 'Wault Swap',
  WETH: 'WETH',
  WIGOSWAP: 'WigoSwap',
  WKLAY: 'WKLAY',
  WKLAY_V10: 'WKLAY',
  WOMBATS: 'Wombat',
  WOMBATSWAP: 'Wombat',
  WOOFI: 'WOOFi',
  WOOFI_V2: 'WOOFi',
  WSTETH: 'Lido',
  XFAI: 'Xfai',
  XSIGMA: 'xSigma',
  YETTI: 'Yetti',
  YOSHI: 'Yoshi',
  ZK_BOB: 'BOB Swap',
  ZKSWAP_FINANCE: 'zkSwap Finance',
  ZRX: '0x',
  ZYBER: 'Zyberswap',
  ZYBER_STABLE: 'Zyberswap',
  ZYBER_V3: 'Synthswap',
};

const zerox = {
  ACryptoS: 'ACryptoS',
  Aave_V2: 'Aave',
  Aave_V3: 'Aave',
  Aerodrome: 'Aerodrome',
  Alienbase: 'AlienBase',
  ApeSwap: 'ApeSwap',
  BakerySwap: 'BakerySwap',
  Balancer: 'Balancer',
  Balancer_V2: 'Balancer',
  Bancor: 'Bancor',
  BancorV3: 'Bancor',
  BaseSwap: 'BaseSwap',
  Beethovenx: 'Beethoven X',
  Belt: 'Belt',
  BiSwap: 'BiSwap',
  CafeSwap: 'CafeSwap',
  Camelot_V3: 'Camelot',
  CheeseSwap: 'CheeseSwap',
  Clipper: 'Clipper',
  ComethSwap: 'ComethSwap',
  Component: 'Component',
  Compound: 'Compound',
  Cream: 'Cream Finance',
  CryptoCom: 'CryptoCom',
  Curve: 'Curve',
  Curve_V2: 'Curve',
  DODO: 'DODO',
  DODO_V2: 'DODO',
  Dfyn: 'Dfyn',
  Ellipsis: 'Ellipsis',
  Eth2Dai: 'Eth2Dai',
  FirebirdOneSwap: 'Firebird',
  GMX: 'GMX',
  IronSwap: 'IronSwap',
  JetSwap: 'JetSwap',
  JulSwap: 'JulSwap',
  KnightSwap: 'KnightSwap',
  Kyber: 'KyberSwap',
  KyberDMM: 'KyberSwap',
  KyberElastic: 'KyberSwap',
  Lido: 'Lido',
  Linkswap: 'Linkswap',
  LiquidityProvider: 'LP',
  MDex: 'MDex',
  MakerPsm: 'Maker',
  Maverick_V1: 'Maverick',
  MobiusMoney: 'Mobius Money',
  Mooniswap: 'Mooniswap',
  MorpheusSwap: 'MorpheusSwap',
  MStable: 'mStable',
  MultiBridge: 'MultiBridge',
  MultiHop: 'MultiHop',
  Native: 'Native',
  Nerve: 'Nerve',
  PancakeSwap: 'PancakeSwap',
  PancakeSwap_V2: 'PancakeSwap',
  PancakeSwap_V3: 'PancakeSwap',
  Pangolin: 'Pangolin',
  Platypus: 'Platypus',
  Polydex: 'Polydex',
  QuickSwap: 'QuickSwap',
  QuickSwap_V2: 'QuickSwap',
  QuickSwap_V3: 'QuickSwap',
  Saddle: 'Saddle',
  ShibaSwap: 'ShibaSwap',
  Shell: 'Shell',
  Smoothy: 'Smoothy',
  SnowSwap: 'SnowSwap',
  SpiritSwap: 'SpiritSwap',
  SpookySwap: 'SpookySwap',
  SushiSwap: 'SushiSwap',
  SushiSwap_V3: 'SushiSwap',
  SwapBased: 'SwapBased',
  Swerve: 'Swerve',
  Synapse: 'Synapse',
  Synthetix: 'Synthetix',
  TraderJoe: 'Trader Joe',
  TraderJoe_V2_1: 'Trader Joe',
  Uniswap: 'Uniswap',
  Uniswap_V2: 'Uniswap',
  Uniswap_V3: 'Uniswap',
  UbeSwap: 'Ubeswap',
  Velodrome: 'Velodrome',
  Velodrome_V2: 'Velodrome',
  WOOFi: 'WOOFi',
  WaultSwap: 'WaultSwap',
  XSigma: 'xSigma',
  Yoshi: 'Yoshi',
};

export const sources = Object.assign({}, oneinch, zerox);
