/* eslint-disable sort-keys-fix/sort-keys-fix */

// Source list must be manually updated with new liquidity sources
// 0x: https://explorer.0xprotocol.org/liquiditySources
// 1inch: https://docs.1inch.io/docs/educational-resources/intermediate/1inch-Liquidity-Sources/
// Accompanying badge icons should be updated at: https://github.com/rainbow-me/assets/tree/master/exchanges

// 1inch
const oneinch = {
  AAVE: 'Aave',
  AAVE_LIQUIDATOR: 'Aave Liquidator',
  AAVE_V2: 'Aave v2',
  AAVE_V3: 'Aave v3',
  BALANCER: 'Balancer',
  BALANCER_V2: 'Balancer v2',
  BANCOR: 'Bancor',
  BLACKHOLESWAP: 'Blackholeswap',
  CHAI: 'Chai',
  CLIPPER: 'Clipper',
  COFIX: 'CoFix',
  COMPOUND: 'Compound',
  CONVERGENCE_X: 'Convergence X',
  CREAMSWAP: 'Creamswap',
  CREAM_LENDING: 'Creamswap Lending',
  CURVE: 'Curve',
  CURVE_V2: 'Curve v2',
  CURVE_V2_ETH_CRV: 'CURVE v2 ETH CRV',
  CURVE_V2_ETH_CVX: 'CURVE v2 ETH CVX',
  CURVE_V2_EURS_2_ASSET: 'Curve v2 EURS',
  CURVE_V2_EURT_2_ASSET: 'CURVE v2 EURT',
  CURVE_V2_SPELL_2_ASSET: 'Curve Spell',
  CURVE_V2_THRESHOLDNETWORK_2_ASSET: 'Curve Threshold',
  CURVE_V2_XAUT_2_ASSET: 'CURVE v2 XAUt',
  CURVE_V2_YFI_2_ASSET: 'Curve Yfi',
  DEFI_PLAZA: 'DeFi Plaza',
  DEFISWAP: 'DeFi Swap',
  DFX_FINANCE: 'Dfx Finance',
  DODO: 'DODO',
  DODO_V2: 'DODO V2',
  DXSWAP: 'Swapr',
  FIXED_FEE_SWAP: 'Fixed Fee Swap',
  FIXED_FEE_SWAP_V3: 'Fixed Rate Swap',
  IEARN: 'yEarn',
  INDEXED_FINANCE: 'Indexed Finance',
  KYBER: 'Kyber',
  KYBER_DMM: 'Kyber DMM',
  LINKSWAP: 'Link Swap',
  LUASWAP: 'Lua Swap',
  MINISWAP: 'Mini Swap',
  MOONISWAP: 'Mooniswap',
  MOONISWAP_MIGRATOR: 'Mooniswap Migrator',
  MSTABLE: 'mStable',
  OASIS: 'Oasis',
  ONE_INCH_LIMIT_ORDER: '1inch Limit Order Protocol v1',
  ONE_INCH_LIMIT_ORDER_V2: '1inch Limit Order Protocol v2',
  ONE_INCH_LIMIT_ORDER_V3: '1inch Limit Order Protocol v3',
  ONE_INCH_LP: '1inch LP v1.0',
  ONE_INCH_LP_1_1: '1inch LP v1.1',
  ONE_INCH_LP_MIGRATOR: '1inch LP v1.0 Migrator',
  ONE_INCH_LP_MIGRATOR_V1_1: '1inch LP v1.0 Migrator',
  PANCAKE_STABLE: 'Pancake Stable',
  PANCAKE_SWAP: 'PancakeSwap',
  PANCAKE_SWAP_V2: 'PancakeSwap v2',
  PANCAKE_SWAP_V3: 'PancakeSwap v3',
  PMM1: 'PMM1',
  PMM2: 'PMM2',
  PMM3: 'PMM3',
  PMM4: 'PMM4',
  PMMX: 'LiqPool X',
  POWERINDEX: 'POWERINDEX',
  PSM: 'PSM',
  QUICKSWAP: 'QuickSwap',
  QUICKSWAP_V3: 'QuickSwap v3',
  SADDLE: 'Saddle Finance',
  SAKESWAP: 'Sake Swap',
  SETH_WRAPPER: 'sETH Wrapper',
  S_FINANCE: 'sFinance',
  SHELL: 'Shell',
  SHIBASWAP: 'Shiba Swap',
  SMOOTHY_FINANCE: 'Smoothy Finance',
  ST_ETH: 'stETH',
  SUSHI: 'Sushiswap',
  SUSHISWAP_MIGRATOR: 'SushiSwap Migrator',
  SWERVE: 'Swerve',
  SYNAPSE: 'Synapse',
  SYNTHETIX: 'Synthetix',
  SYNTHETIX_WRAPPER: 'Synthetix Wrapper',
  TRADERJOE: 'Trader Joe',
  TRADERJOE_V2: 'Trader Joe v2',
  TRADERJOE_V2_1: 'Trader Joe v2.1',
  UNIFI: 'Unifi',
  UNISWAP_V1: 'Uniswap v1',
  UNISWAP_V2: 'Uniswap v2',
  UNISWAP_V2_MIGRATOR: 'Uniswap Migrator',
  UNISWAP_V3: 'Uniswap v3',
  VALUELIQUID: 'Value Liquid',
  WETH: 'WETH',
  WSTETH: 'wstETH',
  XSIGMA: 'xSigma',
  ZRX: '0x',
};

// 0x
const zerox = {
  AaveV2: 'Aave v2',
  AaveV3: 'Aave v3',
  ACryptos: 'ACryptoS',
  ApeSwap: 'ApeSwap',
  BakerySwap: 'BakerySwap',
  Balancer: 'Balancer',
  BalancerV2: 'Balancer v2',
  Bancor: 'Bancor',
  Belt: 'Belt',
  CafeSwap: 'CafeSwap',
  CheeseSwap: 'CheeseSwap',
  Clipper: 'Clipper',
  ComethSwap: 'ComethSwap',
  Component: 'Component',
  Cream: 'CREAM',
  CryptoCom: 'CryptoCom',
  Curve: 'Curve',
  CurveV2: 'Curve v2',
  Dfyn: 'Dfyn',
  Dodo: 'DODO',
  DodoV2: 'DODO V2',
  Ellipsis: 'Ellipsis',
  Eth2Dai: 'Eth2Dai',
  FirebirdOneSwap: 'FirebirdOneSwap',
  IronSwap: 'IronSwap',
  JetSwap: 'JetSwap',
  JulSwap: 'JulSwap',
  Kyber: 'Kyber',
  KyberDmm: 'KyberDMM',
  Lido: 'Lido',
  Linkswap: 'Linkswap',
  LiquidityProvider: 'LP',
  MakerPsm: 'MakerPsm',
  Mooniswap: 'Mooniswap',
  MStable: 'mStable',
  MultiBridge: 'MultiBridge',
  MultiHop: 'MultiHop',
  Native: 'Native',
  Nerve: 'Nerve',
  PancakeSwap: 'PancakeSwap',
  PancakeSwapV2: 'PancakeSwap v2',
  PancakeSwapV3: 'PancakeSwap v3',
  Polydex: 'Polydex',
  QuickSwap: 'QuickSwap',
  QuickSwapV3: 'QuickSwap',
  Saddle: 'Saddle',
  ShibaSwap: 'ShibaSwap',
  Shell: 'Shell',
  Smoothy: 'Smoothy',
  SnowSwap: 'SnowSwap',
  SushiSwap: 'SushiSwap',
  Swerve: 'Swerve',
  Synapse: 'Synapse',
  TraderJoe: 'Trader Joe',
  TraderJoeV2_1: 'Trader Joe v2.1',
  Uniswap: 'Uniswap',
  UniswapV2: 'Uniswap v2',
  UniswapV3: 'Uniswap v3',
  WaultSwap: 'WaultSwap',
  XSigma: 'xSigma',
};

export const sources = Object.assign({}, oneinch, zerox);
